set(MATHCORE_VERSION_MAJOR 2)
set(MATHCORE_VERSION_MINOR 1)
set(MATHCORE_VERSION_PATCH 0)
set(MATHCORE_VERSION "${MATHCORE_VERSION_MAJOR}.${MATHCORE_VERSION_MINOR}.${MATHCORE_VERSION_PATCH}")

message(STATUS "MathCore version: ${MATHCORE_VERSION}")
